#!/usr/bin/env/python
# -*- coding: utf-8 -*-
"""A dictionary of diagnosis for procedures available."""


DX_92025 = {
    'A18.52': 'Tuberculous keratitis',
    'H11.021': 'Central pterygium of right eye',
    'H11.022': 'Central pterygium of left eye',
    'H11.023': 'Central pterygium of eye, bilateral',
    'H11.041': 'Peripheral pterygium, stationary, right eye',
    'H11.042': 'Peripheral pterygium, stationary, left eye',
    'H11.043': 'Peripheral pterygium, stationary, bilateral',
    'H11.811': 'Pseudopterygium of conjuctiva, right eye',
    'H11.812': 'Pseudopterygium of conjuctiva, left eye',
    'H11.813': 'Pseudopterygium of conjuctiva, bilateral',
    'H16.051': 'Mooren\'s corneal ulcer, right eye',
    'H16.052': 'Mooren\'s corneal ulcer, left eye',
    'H16.053': 'Mooren\'s corneal ulcer, bilateral',
    'H16.311': 'Corenal abscess, right eye',
    'H16.312': 'Corneal abscess, left eye',
    'H16.313': 'Corneal abscess, bilateral',
    'H16.321': 'Diffuse interstitial keratitis, right eye',
    'H16.322': 'Diffuse interstitial keratitis, left eye',
    'H16.323': 'Diffuse interstitial keratitis, bilateral',
    'H16.331': 'Sclerosing keratitis, right eye',
    'H16.332': 'Sclerosing kertitis, left eye',
    'H16.333': 'Sclerosing keratitis, bilateral',
    'H16.391': 'Other interstitial and deep keratitis, right eye',
    'H16.392': 'Other interstitial and deep keratitis, left eye',
    'H16.393': 'Other interstitial and deep keratitis, bilateral',
    'H16.8': 'Other keratitis'
}

DX_76514 = {
    'H18.11': 'Bullous keratopathy, right eye',
    'H18.12': 'Bullous keratopathy, left eye',
    'H18.13': 'Bullous keratopathy, bilateral',
    'H18.20': 'Unspecified corneal edema',
    'H40,001': 'Preglaucoma, unspecified, right eye',
    'H40.002': 'Preglaucoma, unspecified, left eye',
    'H40.003': 'Preglaucoma, unspecified, bilateral',
    'H40.011': 'Open angle with borderline findings, low risk, right eye',
    'H40.012': 'Open angle with borderline findings, low risk, left eye',
    'H40.013': 'Open angle with borderline findings, low risk, bilateral',
    'H40.021': 'Open angle with borderline findings, high risk, right eye',
    'H40.022': 'Open angle with borderline findings, high risk, left eye',
    'H40.023': 'Open angle with borderline findings, high risk, bilateral',
    'H40.031': 'Anatomical narrow angle, right eye',
    'H40.032': 'Anatomical narrow angle, left eye',
    'H40.033': 'Anatomical narrow angle, bilateral',
    'H40.041': 'Steroid responder, right eye',
    'H40.042': 'Steroid responder, left eye',
    'H40.043': 'Steroid responder, bilateral',
    'H40.051': 'Ocular hypertension, right eye',
    'H40.052': 'Ocular hypertension, left eye',
    'H40.053': 'Ocular hypertension, bilateral',
    'H40.89': 'Other specified glaucoma',
    'H40.9': 'Unspecified glaucoma',
    'H42': 'Glaucoma in diseases classified elsewhere',
    'Q15.0': 'Congenital glaucoma',
    'T86.840': 'Corneal transplant rejection',
    'T86.841': 'Corneal transplant failure',
    'Z98.41': 'Cataract extraction status, right eye',
    'Z98.42': 'Cataract extraction status, left eye',
    'Z98.83': 'Filtering (vitreous) bleb after glaucoma surgery status'
}

DX_92235 = {
    'B20': 'Human immunodeficiency virus [HIV] disease',
    'B58.01': 'Toxoplasma chorioretinitis',
    'C69.21': 'Malignant neoplasm of right retina',
    'C69.22': 'Malignant neoplasm of left retina',
    'C69.31': 'Malignant neoplasm of right choroid',
    'C69.32': 'Malignant neoplasm of left choroid',
    'D18.09': 'Hemangioma of other sites',
    'D31.21': 'Benign neoplasm of right retina',
    'D31.22': 'Benign neoplasm of left retina',
    'D31.31': 'Benign neoplasm of right choroid',
    'D31.32': 'Benign neoplasm of left choroid',
    'G35': 'Multiple sclerosis',
    'G93.2': 'Benign intracranial hypertension',
    'H15.031': 'Posterior scleritis, right eye',
    'H15.032': 'Posterior scleritis, left eye',
    'H15.033': 'Posterior scleritis, bilateral',
    'H35.011': 'Changes in retinal vascular appearance, right eye',
    'H35.012': 'Changes in retinal vascular appearance, left eye',
    'H35.013': 'Changes in retinal vascular appearance, bilateral',
    'H35.021': 'Exudative retinopathy, right eye',
    'H35.022': 'Exudative retinopathy, left eye',
    'H35.023': 'Exudative retinopathy, bilateral',
    'H35.041': 'Retinal micro-aneurysms, unspecified, right eye',
    'H35.042': 'Retinal micro-aneurysms, unspecified, left eye',
    'H35.043': 'Retinal micro-aneurysms, unspecified, bilateral',
    'H35.051': 'Retinal neovascularization, unspecified, right eye',
    'H35.052': 'Retinal neovascularization, unspecified, left eye',
    'H35.053': 'Retinal neovascularization, unspecified, bilateral',
    'H35.09': 'Other intraretinal microvascular abnormalities',
    'H35.21': 'Other non-diabetic proliferative retinopathy, right eye',
    'H35.22': 'Other non-diabetic proliferative retinopathy, left eye',
    'H35.23': 'Other non-diabetic proliferative retinopathy, bilateral',
    'H35.31': 'Nonexudative age-related macular degeneration',
    'H35.32': 'Exudative age-related macular degeneration',
    'H35.33': 'Angiod streaks of macula'
}

DX_76512 = {
    'C69.01': 'Malignant neoplasm of right conjuctiva',
    'C69.02': 'Malignant neoplasm of left conjuctiva',
    'C69.11': 'Malignant neoplasm of right cornea',
    'C69.12': 'Malignant neoplasm of left cornea',
    'C69.21': 'Malignant neoplasm of right retina',
    'C69.22': 'Malignant neoplasm of left retina',
    'C69.31': 'Malignant neoplasm of right choroid',
    'C69.32': 'Malignant neoplasm of left choroid',
    'H15.011': 'Anterior scleritis, right eye',
    'H15.012': 'Anterior scleritis, left eye',
    'H15.013': 'Anterior scleritis, bilateral',
    'H15.021': 'Brawny scleritis, right eye',
    'H15.022': 'Brawny scleritis, left eye',
    'H15.023': 'Brawny scleritis, bilateral',
    'H15.041': 'Scleritis with corneal involvement, right eye',
    'H15.042': 'Scleritis with corneal involvement, left eye',
    'H15.043': 'Scleritis with corneal involvement, bilateral',
    'H15.051': 'Scleromalacia perforans, right eye',
    'H15.052': 'Scleromalacia perforans, left eye',
    'H15.053': 'Scleromalacia perforans, bilateral',
    'H18.11': 'Bullous keratopathy, right eye',
    'H18.12': 'Bullous keratopathy, left eye',
    'H18.13': 'Bullous keratopathy, bilateral',
    'H18.211': 'Corneal edema secondary to contact lens, right eye',
    'H18.212': 'Corneal edema secondary to contact lens, left eye',
    'H18.213': 'Corneal edema secondary to contact lens, bilateral',
    'H18.221': 'Idiopathic corneal edema, right eye',
    'H18.222': 'Idiopathic corneal edema, left eye',
    'H18.223': 'Idiopathic corneal edema, bilateral',
    'H18.231': 'Secondary corneal edema, right eye',
    'H18.232': 'Secondary corneal edema, left eye',
    'H18.233': 'Secondary corneal edema, bilateral'
}

DX_76519 = {
    'E10.36': 'Type 1 diabetes mellitus with diabetic cataract',
    'E11.36': 'Type 2 diabetes mellitus with diabetic cataract',
    'E13.36': 'Other specified diabetes mellitus with diabetic cataract',
    'H25.011': 'Cortical age-related cataract, right eye',
    'H25.012': 'Cortical age-related cataract, left eye',
    'H25.013': 'Coritcal age-related cataract, bilateral',
    'H25.031': 'Anterior subcapsular polar age-related cataract, right eye',
    'H25.032': 'Anterior subcapsular polar age-related cataract, left eye',
    'H25.033': 'Anterior subcapsular polar age-related cataract, bilateral',
    'H25.041': 'Posterior subcapsular polar age-related cataract, right eye',
    'H25.042': 'Posterior subcapsular polar age-related cataract, left eye',
    'H25.043': 'Posterior subcapsular polar age-related cataract, bilateral',
    'H25.11': 'Age-related nuclear cataract, right eye',
    'H25.12': 'Age-related nuclear cataract, left eye',
    'H25.13': 'Age-related nuclear cataract, bilateral',
    'H25.21': 'Age-related cataract, morgagnian type, right eye',
    'H25.22': 'Age-related cataract, morganinan type, left eye',
    'H25.23': 'Age-related cataract, morganinan type, bilateral',
    'H25.811': 'Combined forms of age-related cataract, right eye',
    'H25.812': 'Combined forms of age-related cataract, left eye',
    'H25.813': 'Combined forms of age-related cataract, bilateral',
    'H25.89': 'Other age-related cataract',
    'H25.9': 'Unspecified age-related cataract',
    'H28': 'Cataract in diseases classified elsewhere',
    'Q12.0': 'Congenital cataract',
    'Q12.1': 'Congenital displaced lens',
    'Q12.2': 'Coloboma of lens',
    'Q12.3': 'Congential aphakia',
    'Q12.4': 'Spherophakia',
    'Q12.8': 'Other congenital lens malformations'
}
